name: newrelease

on:

  pull_request:
    branches:
      '**'
      
  workflow_dispatch:

# ---------- all branches except main

jobs:
  pester-test:
    name: Pester test
    # ----- skip job if 'skip ci' in commit and if it is the main branch
    if: "!contains(github.event.commits[0].message, '[skip ci]')"
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      
      - name: pester-tests-report
        uses: zyborg/pester-tests-report@v1.3.3
        with:
          include_paths: Tests
          github_token: ${{ secrets.GITHUB_TOKEN }}

  tagmain:
    name: tag main branch
    needs: pester-test 
    if: "${{ success() }} && endswith( github.ref,'dev' )"
    runs-on: ubuntu-latest
    steps:
      - name: info
        run: |
          echo "Branch = ${{ github.event.pull_request.head.ref }}"
          echo "Trigger = ${{ github.event_name }}"
          echo "Trigger Ation = ${{ github.event.action }}"
          echo "Merge = ${{ github.event.pull_request.merged }}"
    
      - name: Check out repository code
        uses: actions/checkout@v2        
        
      - name: GetRepoVersion
        id: GetRepoVer
        uses: jeffbuenting/GetRepoVersion@getfile
        
      - name: tag
        run: |
          git config --global user.name 'github actions'      
          git config --global user.email 'actions@github.com'
          git tag -a v${{ steps.GetRepoVer.outputs.version }} -m "v${{ steps.GetRepoVer.outputs.version }}"
        
  #    - name: Commit
  #      run: |
  #        git status
  #        git config --global user.name 'github actions'      
  #        git config --global user.email 'actions@github.com'
  #        git ls-files --others --exclude-standard
  #        git commit -am "skip ci - main tag: ${{ steps.GetRepoVer.outputs.version }}"
  #        git push  
    