# This is a basic workflow to help you get started with Actions

name: UnitTest

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      '**'
  pull_request:
    branches:
      '**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# ---------- all branches except main

jobs:
  pester-test:
    name: Pester test
    # ----- skip job if 'skip ci' in commit and if it is the main branch
    if: "!contains(github.event.commits[0].message, '[skip ci]') && !endswith(github.ref,'main')"
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      
      - name: pester-tests-report
        uses: zyborg/pester-tests-report@v1.3.3
        with:
          include_paths: Tests
          github_token: ${{ secrets.GITHUB_TOKEN }}
        
  UpdateModuleVersion:
    name: UpdatesModuleVersion and returns that Version
    needs: pester-test
    if: ${{ success() }} && github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2        
        
      - name: GetRepoVersion
        if: success()
        id: GetRepoVer
        uses: jeffbuenting/GetRepoVersion@getfile

      - name: IncreaseVersion
        id: IncreaseVer
        shell: bash
        run: |
            CurVer=${{ steps.GetRepoVer.outputs.version }}
            IFS='.'
            read -a SplitVer <<<"$CurVer"
            Major=$((SplitVer[0]))
            Minor=$((SplitVer[1]))
            Build="$((SplitVer[2] + 1))"
            NewVer="$Major.$Minor.$Build"
            unset IFS
            echo "::set-output name=version::$NewVer"
         
      - name: Show Version
        run: |
          echo "NewVer = ${{ steps.IncreaseVer.outputs.version }}"
  
      - name: UpdateModuleVersion
        uses: ./
        with: 
          vertype: ${{ steps.GetRepoVer.outputs.versiontype }}
          newver: ${{ steps.IncreaseVer.outputs.version }}
           
      - name: UpdateReadmeVersionBadge
        uses: jeffbuenting/UpdateCustomBadge@jeffbuenting-patch-1
        with:
          filename: 'README.md'
          label: 'Version'
          message: ${{ steps.IncreaseVer.outputs.version }}
          
      - name: Commit
        if: ${{ success() }}
        run: |
          git status
          git config --global user.name 'github actions'      
          git config --global user.email 'actions@github.com'
          git ls-files --others --exclude-standard
          git commit -am "skip ci - Commit Updated files to Repo"
          git push
 
 # ---------- Main branch
 
  TagMain:
    name: tags the main branch
    needs: pester-test
    if: endswith( github.ref,'main' ) && github.event_name == 'pull_request' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2        
        
      - name: GetRepoVersion
        id: GetRepoVer
        uses: jeffbuenting/GetRepoVersion@getfile
        
      - name: tag
        run: git tag -a v${{ steps.GetRepoVer.outputs.version }} -m "v${{ steps.GetRepoVer.outputs.version }}"
        
      - name: Commit
        run: |
          git status
          git config --global user.name 'github actions'      
          git config --global user.email 'actions@github.com'
          git ls-files --others --exclude-standard
          git commit -am "skip ci - main tag: ${{ steps.GetRepoVer.outputs.version }}"
          git push  