# This is a basic workflow to help you get started with Actions

name: UnitTest

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      '**'
  pull_request:
    branches:
      '**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  pester-test:
    name: Pester test
    if: "!contains(github.event.commits[0].message, '[skip ci]')"
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      
      - name: pester-tests-report
        uses: zyborg/pester-tests-report@v1.3.3
        with:
          include_paths: Tests
          github_token: ${{ secrets.GITHUB_TOKEN }}
        
  UpdateModuleVersion:
    name: UpdatesModuleVersion and returns that Version
    needs: pester-test
    if: ${{ success() }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2        
        
      - name: GetRepoVersion
        if: success()
        id: GetRepoVer
        uses: jeffbuenting/GetRepoVersion@getfile

      - name: IncreaseVersion
        id: IncreaseVer
        shell: bash
        run: |
            CurVer=${{ steps.GetRepoVer.outputs.version }}
            IFS='.'
            read -a SplitVer <<<"$CurVer"
            Major=SplitVer[0]
            Minor=SplitVer[1]
            Build="$((SplitVer[2] + 1))"
            NewVer=$Major.Minor.Build
            unset IFS
            echo $NewVer
            echo '::set-output name=version::${NewVer}'
         
      - name: Show Version
        run: |
          echo 'NewVer = (should be on the line below)'
          echo ${{ steps.IncreaseVer.outputs.version }}
